### ISSUE TITLE
Add new pets 

### ISSUE THREAD

**Issue by erwinqxy** [AllardQuek/Purrductivity#12]
- add the option to select and upload pets!

**Comment by AllardQuek** [comment]
References
1. https://developer.chrome.com/docs/extensions/mv3/messaging/
2. https://stackoverflow.com/questions/29926598/sendmessage-from-popup-to-content-js-not-working-in-chrome-extension
3. https://stackoverflow.com/questions/49511012/how-to-send-the-message-from-popup-html-to-content-script

Issues Faced: https://developer.chrome.com/docs/extensions/mv3/messaging/#simple
1. `id` attribute not found 
<img width="739" alt="image" src="https://github.com/AllardQuek/Purrductivity/assets/40263305/b9a0f215-dab7-46ee-a76e-c818681f02a5">
2. `console.log` not showing in console
<img width="730" alt="image" src="https://github.com/AllardQuek/Purrductivity/assets/40263305/79f904e3-da78-4605-94c9-5a4c7f76cb50">

**Comment by erwinqxy** [comment]
Very good work @AllardQuek
